RM = rm -f

default:
	gcc -o readTest readTest.c
	gcc -o writeTest writeTest.c
	gcc -o ioctlTest ioctlTest.c
	gcc -o nusersTest nusersTest.c
	gcc -o ononblockTest ononblockTest.c
	gcc -o selectTest selectTest.c

clean veryclean:
	$(RM) readTest
	$(RM) writeTest
	$(RM) ioctlTest
	$(RM) nusersTest
	$(RM) ononblockTest
	$(RM) selectTest
